### ISSUE TITLE
Check out viability of virtual currency administrator role 

### ISSUE THREAD

**Issue by dazzaji** [HumanDynamics/BlockCreditUnion#1]
- https://www.fincen.gov/statutes_regs/guidance/html/FIN-2013-G001.html
- https://www.fincen.gov/news_room/rp/rulings/pdf/FIN-2015-R001.pdf

**Comment by FellowTraveler** [comment]
Best solution is to use someone who's already compliant (like an existing credit union.)

**Comment by dazzaji** [comment]
Also:
- https://www.fincen.gov/statutes_regs/guidance/html/FIN-2016-G002.html
- https://www.fincen.gov/statutes_regs/guidance/html/FIN-2016-G001.html
- https://www.fincen.gov/news_room/rp/rulings/pdf/FIN-2014-R001.pdf
- https://www.fincen.gov/news_room/rp/rulings/pdf/FIN-2014-R002.pdf
- https://www.fincen.gov/statutes_regs/guidance/html/FIN-2014-G002.html
