### ISSUE TITLE
Demo of Wallets and Blockchain Payment Project In Sprint Repo

### ISSUE THREAD

**Issue by dazzaji** [HumanDynamics/BlockCreditUnion#11]
Here: https://github.com/CIVICS/GreatBlockchainBakeOffOf2016/issues/1

Akshith G generously volunteered to assist with demo of top blockchain wallets and demo of blockchain payment transaction ending with US Dollars to bank account or paypal or similar!

**Comment by akshithg** [comment]
@dazzaji Here is some help from coinbase for linking a US bank account https://support.coinbase.com/customer/portal/articles/1944900-how-do-i-verify-a-us-bank-account

Let me know if you run into any problem.

**Comment by dazzaji** [comment]
I'm surprised the ability to integrate a service to provide payment into an account requires sharing the home banking username and password that also happens to serve as the identify and authentication credential to empty a bank account.  These credentials are explicitly never permitted to be shared with any third party for any reason.  It seems as though the financial services sector has still not heard the good news about OAuth to tokenize proof of identification, authentication of an account holder and with nearly no effort (a second "scope") to provide proof of account holder authorization to conduct transactions with their account. If it's inefficient or too scary for a bank to rely on OAuth 2 for proof of authorization for a payment from a customer to be debuted from their account perhaps it is at least acceptable as verifiable evidence of the customer desire to have a payment deposited into their account.  I appreciate there are AML and other complexities in play with accepting deposits but the stakes are far lower and it is not especially hard to trigger a customer second factor approval through existing web baking and mobile banking apps.  The idea that a bank account holder must actually share their user name and password in order to receive s deposit is very surprising. 

Several years ago web identity and web security groups fixed on the Mint site as a great site but indicative of a major problem on the web because it required username and password sharing for purposes of basic app/service integrations (Mint was/is a portal site to help people aggregate their banking information across several institutions into one dashboard). As I recall, web banking user name and password sharing was widely agreed to be the poster child of an unacceptable practice and it was a common example used from many a podium when modern OAuth was being socialized and propagated several years ago. It is a poignant observation that whole so many other industries and sectors have benefited from adopting OAuth 2 and now OpenID Connect to fix the lack of a standard method to tokenize AuthN/AuthZ meanehile banks - the poster child problem statement  - apparently remains fundamentally unchanged. 

I appreciate the link and description page but I must decline the option to provide my username and password to my bank account because that would be a really bad practice and the opposite of "good" practices I hope to demonstrate for use of Blockchain as part of an "improvement" of the process for payment of legal tender.

**Comment by h0pbeat** [comment]
Plus sharing username/password breaks immediately once 2FA is enabled on
the bank account, which should and is becoming a standard....

Arek

**Comment by h0pbeat** [comment]
Plus sharing username/password breaks immediately once 2FA is enabled on the bank account, which should and is becoming a standard....

**Comment by dazzaji** [comment]
How about payment to PayPal?  Shall we give that a try and then we can use the money to buy a domain name at godaddy and I can create a "new small business" pointing the domain at a startup in-a-box template on GitHub Pages... in a few minutes before the astonished eyes of those seeing the speed and elegance of applying some custom variable data to bootstrap alpha 4 template and pointing the DNS A-Record at the registrar aand receiving the CNAME in a root file. Always a good time. Or I could spend the PayPal on a movie or some other thing that demonstrates immediate transaction of actual commercial value. So... how about pivoting to PayPal (and elevating the use of OpenID Connnect on the roadmap for the Automated Credit Union prototype to demo a more usable less embarrassingly deficient model for digital financial institutions)?

**Comment by akshithg** [comment]
This is clearly, banks being very slow at adopting tech. I'm actually surprised. I missed this the first time cuz, when I glanced through it, I interpreted it as bank doing a verification before granting the 3rd party (coinbase) an access token.

In India to withdraw BTC as Indian Rupee, I just have to provide my bank account number and IFSC (Indian Financial System Code). Works very well.

I definitely would live pivoting to PayPal. Here is a link that might come handy just in case you need it. https://support.coinbase.com/customer/portal/articles/2458534 

Dazza, How do we go about the Demo? Will you or folks there help create a video? Conibase requires the individual to be a US citizen to use its services.

I can create a demo for other types of wallets, which are more independent and not tied to a service like coinbase.

**Comment by dazzaji** [comment]
Arek scores a major point re 2FA. It's time for another pointed blog post or medium article again. 

And now this: http://applehelpwriter.com/2016/08/29/discovering-how-dropbox-hacks-your-mac/

**Comment by dazzaji** [comment]
Hi Akshith - Can you make a list of the Bitcoin and Etheteum wallets you are planning to demo and share some links to videos as they come online? 

Re Coinbase, let's give a micro payment terminating to PayPal a try tomorrow. What time spans wound work for you?

**Comment by akshithg** [comment]
Hi Dazza, these are the various wallets:
1. Hot Wallets vs Cold wallets
2. Hardware wallet: Trezor
3. Desktop wallet with full node (Bitcoin core)
4. Light wallets (Bit Go and Multibit HD,  differ in terms of validation)
5. Web Wallets (Coinbase/Circle)

1-4 are the ones i'd want to demo. I chose these so that I can cover why we have such variety and what are the use cases of each.

I'll add the links as and when I make the video/presentation available.

[UPDATE]
Q: How long does the whole demo have to be?

**Comment by akshithg** [comment]
Completed.
