### ISSUE TITLE
Preliminary assessment of automated regulatory filing approach

### ISSUE THREAD

**Issue by dazzaji** [HumanDynamics/BlockCreditUnion#6]
Please take a look at the 2017 technical standards for filing "hmda" reports from financial institutions to their government regulators. The info for how to file is at:  www.ffiec.gov/hmda/

Please start to consider how best to accomplish the following: 

Step by step process for a US financial institution of the federally chartered credit union type to:
- Maintain and update the required hmda on a loan by loan and event by event basis in an authoritative data store that is set up by design to always and exactly provide then up to date required hmda data in precisely the structure and format expected for filing with the regulator (as defined in the GitHub repo above); and 
- Process for successfully transmitting properly formatted and structured hmda data to the regulator through a standard US government API (if that API info isn't easily findable let me know and I'll dig it out for you); and 
- Consider options that would world best in the cloud foundry environment for managing the transmission of hmda filings with a fully automated process (i.e. operating bases on listeners and event based or time based triggers, maintaining through acknowledged and confirmed completion a set of handshake, transaction and receipt communications protocols to ensure full lifecycle filing compliance without human review or approval unless an error or emergency alert condition requires and sends notices to ensure manual intervention by appropriate staff of the financial institution; and lastly,
- Use of a Blockchain to enter evidence of the content of each hmda filing and evidence of that the filing was successfully reported to the regulator (leverage the available data through the API for most of this) and you can assume for purposes of this project receipt of a message digest of the filing data received by the government regulator and encrypted with a private key of that regulator as evidence that the filing was definitely, successfully and conclusively completed. 

We will be discussing problems and prospects in this issue. 

By way of context for this preliminary issue: This item will become part of a more general set of regulatory filings and reporting which itself is part of a broader regulatory compliance. Regulatory Complaince is one of the key pillars of the next generation core architectural for a fully automated business of the financial institution legal entity type. For the moment, simply becoming familiar with this specific standard and important data set and related reporting process is a good initial exposure to relevant information and upcoming challenges and could provide a basis for starting to hack at various aspects of the project that are likely to be of value (direct or indirect) for later work. 

Go for it.

**Comment by bcmfailforward** [comment]
Very Interesting,

Re:

```
review or approval unless an error or emergency alert condition
requires and sends notices to ensure manual intervention by
```

Your familiar with Triple Entry Accounting....  What comes to the top of my mind is
that the 3rd Blockchain ledger IS not only an arbiter but also one of the the error propagators....

For a Fault Redundant System you shout have at least 2 parties with an arbiter in the middle to resolve disputes
If ALL 3 are also send error messages to the other 2 then no one can say they didn't get the error message from the other party....

You not only have proof the error occured  But proof the message was sent..... This becomes interesting if the 3 rd Party {or 4th} also a regulator.
There is a deeper discussion here.

**Comment by bcmfailforward** [comment]
Ideally What you really want to do is NOT send a .txt file but a blockchain address which reads the underlying data... it don't seem like they are ready for that ...  But I think that's what we should be striving Regulators to accept....  I feel a deeper discussion here too.

**Comment by dazzaji** [comment]
Brenden - this issue is related to accomplishing the task identified.  You are more than welcome to join the fun of this thread if you'd like to grab an oar and give it a try.  

Also welcome and appreciated is more general discussion on the ideas and topics related to this issue, not focused on achievement of the task identified by the issue. The correct forum for that type of general discussion is the Computable Law Public Forum, a new Google Group which you can sign up for right here: https://groups.google.com/d/forum/computable  I've created a special topic in that forum for this thread on automated and autonomous actions intended to operate without human review or approval.  The thread is titled: "The Anatomy of Automated and Autonomous Actors and Actions" and I'd recommend you start right there.

**Comment by dazzaji** [comment]
For reference, filing instructions for submission via web interface, email and hard disk to NCUA are detailed here: www.ffiec.gov/hmda/contactNCUA.htm

**Comment by bcmfailforward** [comment]
Dazza, Thanks for setting up the Google Groups and adding me as #2
I am going add some stuff and drive it forward these issues of automated and perhaps autonomous is something I feel really passionate about....I believe there is great opportunity for all in what's to come IF the spigots of regulation are set right!!

Thanks,
B.

**Comment by bcmfailforward** [comment]
Thanks.

**Comment by akshithg** [comment]
Dazza,
I now understand HMDA.

Coming to the points that you have mentioned above, this is what I've learnt
1. I looked into the **File Specifications** under the **How to file** section. [This](http://www.ffiec.gov/hmda/pdf/spec2016.pdf) is the pdf i've looked into for the details on how a financial institute can file in an electronic format. From the pdf what I gather is
   - the  HMDA Data Entry Software has to be used to generate an encrypted file which holds all the data, which is then mailed or submitted via web.
   - if the data is generated outside the application (ie as per the Transmittal Sheet and the Loan/Application Register) then the resulting file must be encrypted using the HMDA DES and then submitted.
   
   So in the submission process the HMDA DES tool is involved. It being a **Windows executable file** we'll have to figure a web equivalent. 
2. The documents doesn't address the exact standards of encryption or an endpoint to which the data must be submitted. Can you help me figure this out?
3. I'm not sure to what extent we can automate the process end-to-end. In the pdf that I had mentioned earlier, please look at page 6 point 11. We'll need to discuss all the possible consequences and figure a way to at least communicate the status to the user in an automated fashion.
4. On a successful submission we can always group the message digests into a `merkle tree` and anchor the `merkle root` at regular intervals. Just a thought, we can find more ways to do it.

**Comment by bcmfailforward** [comment]
Hi akshithg, Yes you are right they dont specify the crypto method. Perhaps a call I found this-

I am a HUD reporter, who do I contact for assistance?

For assistance with HMDA processing, Contact Us. Questions regarding the discontinuance of FHA data collection and negative reports should be directed to Jerry Fasick of HUD at 202-755-7500 x7540. 

Also your merkle tree prof of submission seems like a step in the right direction. 
~Brenden.

**Comment by akshithg** [comment]
Thanks for the feedback Brenden. Im not based out of US, is there anyway I can get help in figuring out the issues we have from the concerned?

**Comment by dazzaji** [comment]
Akshith - there are several items you can make progress on... please get going on those and keep reporting. Move forward and be assured the items are quite separatable for purposes of you making progress with automated filings using this documented design pattern, data structure, message protocol set and data model/taxonomy.  Assume plain text email for the moment and pull a new issues called "plan to prototype automated filing" reflecting your best take on how to make it work as best you can on Cloud Foundy. We will move forward from your action plan.

**Comment by dazzaji** [comment]
The initial assessment has been successfully completed.  For next steps, refer to https://github.com/HumanDynamics/BlockCreditUnion/issues/7
